services:
  syra-flask-drools:
    build:
      context: syra-flask-drools
    ports:
      - 5000:5000
    environment:
      - WEBSERVICE_URL=http://syra-drools:8080/syra
    depends_on:
      - syra-drools
    networks:
      - drools_network

  syra-drools:
    build:
      context: syra-drools
    ports:
      - 8080:8080
    networks:
      - drools_network
      
networks:
  drools_network:
